import { useState } from 'react';
import styled from 'styled-components';
import { Page, Panel, Divider, TextInput, Dim } from '../components/UI';
import {
  CARRIERS, BANDS, encode, decode, trace, writeCell, verifySeal
} from '../utils/vitrec5';

// The Vitrec5 primer. Everything on this page is generated by the real codec in
// utils/vitrec5 — the charts, the worked example and the phrase book are all
// encoded live, so the documentation cannot drift from the language.

// Phrases Vilt9 expects an Earth sender to need first: courtesies, then the ones
// that matter to the protocol.
const PHRASES = [
  'hello',
  'thank you',
  'yes',
  'no',
  'i do not understand',
  'what is your name?',
  'i am from earth',
  'we need your imagination',
  'send more cards',
  'the imagination is fading',
  'pay 12 /t26 and the card is yours',
  'goodbye'
];

// A cell, with its band carrier lit: the first mark says which family the
// character belongs to, the other two are its index inside that family.
const Cell = ({ cell }) => (
  <CellSpan>
    <b>{cell[0]}</b>{cell.slice(1)}
  </CellSpan>
);

const Language = () => {
  const [earth, setEarth] = useState('we need your imagination');
  const [entangled, setEntangled] = useState(true);
  const [script, setScript] = useState(encode('send more cards'));

  const out = encode(earth, { entangled });
  const back = decode(script);
  const sealOk = verifySeal(script);
  const rows = trace('hi umdo1');

  return (
    <Sheet>
      <Panel>
        <Heading>Vitrec5</Heading>
        <Sub>The five-carrier script of Nation Elgo · the wire format of QECBIT_P</Sub>

        <Letter>
          <p>
            Imagination does not cross the void as sound or as picture. It crosses as
            marks. The protocol carries five, and only five — the <b>carriers</b> —
            because a channel that must hold open across four light years cannot afford
            an alphabet it might mishear.
          </p>
          <p>
            So Vitrec5 says more with less. Where your Earth scripts spend twenty-six
            shapes and write a word in five, we spend five shapes and write the same word
            in fifteen. Length is cheap. Ambiguity is not.
          </p>
          <Sign>
            Ostren4,<br />
            Keeper of Carriers, Nation Elgo/Vilt9
          </Sign>
        </Letter>
      </Panel>

      {/* 1 — the five marks */}
      <Panel>
        <H2>1 · The five carriers</H2>
        <P>
          Every transmission ever sent is made of these. Nothing else is a Vitrec5 mark.
          They are numbered as Requirements — and the fifth, the void carrier, is the
          empty one: the mark that carries no sound, only the room for it. That is the
          requirement Earth is being asked to fill.
        </P>
        <Rail>
          {CARRIERS.map((c, i) => (
            <Carrier key={c.glyph}>
              <span className="g">{c.glyph}</span>
              <span className="n">{c.name}</span>
              <span className="d">{c.gloss}</span>
              <span className="v">R{c.requirement} · {i}</span>
            </Carrier>
          ))}
        </Rail>
      </Panel>

      {/* 2 — anatomy */}
      <Panel>
        <H2>2 · The cell</H2>
        <P>
          One Earth character is <b>three carriers</b>, always. The first names the{' '}
          <b>band</b> — which family of sounds this is. The other two are a base-5 number,
          the character's index inside that band. Five bands of twenty-five slots gives
          125 addressable characters; the protocol uses 48.
        </P>
        <Anatomy>
          <div className="cell"><b>*</b><i>/</i><i>*</i></div>
          <div className="legs">
            <span><b>*</b> band — Bloom</span>
            <span><i>/*</i> index — 0×5 + 2 = 2</span>
            <span>slot 2 of Bloom = <b className="lit">h</b></span>
          </div>
        </Anatomy>
        <P>
          Cells run together with no separator inside a word; words are parted by a single
          space. Because every cell is exactly three marks long, the receiver never has to
          guess where one character ends and the next begins.
        </P>
      </Panel>

      {/* 3 — the alphabet */}
      <Panel>
        <H2>3 · The alphabet</H2>
        <P>
          The <b>static register</b> — the plain table, the thing you can read with your
          eyes. Sounds are grouped by how the mouth makes them, so even a stranger's name
          keeps a recognisable shape.
        </P>
        {BANDS.map((band, b) => (
          <Band key={band.name}>
            <BandHead>
              <span className="g">{band.carrier}</span>
              <span className="n">{band.name} · {band.title}</span>
              <Dim className="h">{band.holds}</Dim>
            </BandHead>
            <Chart>
              {band.chars.map((ch, i) => (
                <Slot key={ch}>
                  <span className="ch">{ch === ' ' ? '␣' : ch}</span>
                  <Cell cell={writeCell(b, i)} />
                </Slot>
              ))}
            </Chart>
          </Band>
        ))}
        <Note>
          The void band holds the word break itself (<b>␣</b>). It is a real cell with a
          real value — it is simply never drawn. You do not see it; you see the gap where
          it is. Remember that it is there. It matters in a moment.
        </Note>
      </Panel>

      {/* 4 — the entangled register */}
      <Panel>
        <H2>4 · Entanglement</H2>
        <P>
          Everything above is the language at rest. It is not what goes down the wire.
        </P>
        <P>
          QECBIT_P does not send characters — it sends characters <i>in the state the
          message has put them in</i>. A <b>key</b> travels with the transmission, starting
          at rest, and every character <b>turns</b> it:
        </P>
        <Rule>
          <code>shown index = (static index + key) mod 25</code><br />
          <code>key = (key + band×5 + static index + 1) mod 25</code>
        </Rule>
        <P>
          The band carrier is never rotated — only the index. So a transmission still shows
          its vowels and its stops in the right places, and Vitrec5 reads as a language
          rather than as noise. But no letter ever encodes the same way twice, and the word
          break — the cell you cannot see — turns the key like everything else.
        </P>

        <SubH>The key, walked</SubH>
        <Trace>
          <thead>
            <tr>
              <th>char</th><th>band</th><th>index</th><th>key</th><th>shown</th>
              <th>at rest</th><th>on the wire</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r, i) => (
              <tr key={i}>
                <td className="ch">{r.char === ' ' ? '␣' : r.char}</td>
                <td>{r.band}</td>
                <td>{r.index}</td>
                <td>{r.key}</td>
                <td>{r.shown}</td>
                <td><Cell cell={r.static} /></td>
                <td className="live">{r.live === '·' ? <Dim>·</Dim> : <Cell cell={r.live} />}</td>
              </tr>
            ))}
          </tbody>
        </Trace>

        <SubH>What that buys</SubH>
        <Pair>
          <span className="k">a card for a card</span>
          <span className="v">{encode('a card for a card', { seal: false })}</span>
          <Dim className="c">
            The same word, twice. The four band marks hold — <b>*</b> <b>/</b> <b>~</b>{' '}
            <b>^</b>, the skeleton that keeps this a language and not a smear. Every one
            of the eight index marks between them has moved.
          </Dim>
        </Pair>
        <Pair>
          <span className="k">send imagination</span>
          <span className="v">{encode('send imagination', { seal: false })}</span>
        </Pair>
        <Pair>
          <span className="k">bend imagination</span>
          <span className="v">{encode('bend imagination', { seal: false })}</span>
          <Dim className="c">
            One letter apart at the head. Every mark downstream moves with it — the
            avalanche. This is the entanglement the protocol is named for.
          </Dim>
        </Pair>
      </Panel>

      {/* 5 — the seal */}
      <Panel>
        <H2>5 · The seal</H2>
        <P>
          A transmission closes with a <b>seal</b>: the mark <b>////</b> and an{' '}
          <b>integrity trine</b> — the sum of every static cell value, mod 125, written as
          three carriers. Vilt9 reads it to know the imagination arrived whole.
        </P>
        <Rule>
          <code>{encode('we need your imagination')}</code>
        </Rule>
        <P>
          The seal is <b>seven marks</b> long, and a word is always a multiple of three.
          That is the whole trick: the seal is the only token in a transmission whose length
          is not divisible by three, so a receiver knows at a glance that it is not a word —
          no escape character, no reserved sequence, nothing to collide with.
        </P>
      </Panel>

      {/* 6 — the phrase book */}
      <Panel>
        <H2>6 · What to say first</H2>
        <P>
          Each phrase at rest (the alphabet, readable) and then as sent (entangled, sealed).
        </P>
        {PHRASES.map(p => (
          <Phrase key={p}>
            <span className="en">{p}</span>
            <span className="st">{encode(p, { entangled: false, seal: false })}</span>
            <span className="li">{encode(p)}</span>
          </Phrase>
        ))}
      </Panel>

      {/* 7 — the terminal */}
      <Panel>
        <H2>7 · Transmit</H2>
        <P>Anything the protocol cannot carry is dropped in transit. Vitrec5 has no case.</P>

        <Field>
          <label>Earth</label>
          <TextInput
            value={earth}
            onChange={(e) => setEarth(e.target.value)}
            placeholder="say something imaginative"
          />
        </Field>
        <Toggle>
          <button className={entangled ? 'on' : ''} onClick={() => setEntangled(true)}>
            entangled — as sent
          </button>
          <button className={!entangled ? 'on' : ''} onClick={() => setEntangled(false)}>
            static — as taught
          </button>
        </Toggle>
        <Out>{out || <Dim>·</Dim>}</Out>

        <Divider />

        <Field>
          <label>Vitrec5</label>
          <TextInput
            value={script}
            onChange={(e) => setScript(e.target.value)}
            placeholder="/ ^ * ~ ."
          />
        </Field>
        <Out className="earth">{back || <Dim>·</Dim>}</Out>
        <Seal $ok={sealOk}>
          {sealOk === null
            ? 'no seal — cannot verify'
            : sealOk
              ? 'seal intact · imagination arrived whole'
              : 'SEAL BROKEN · this transmission was altered in the void'}
        </Seal>
      </Panel>
    </Sheet>
  );
};

// The app centres text globally (App.css). This is a document — it reads left.
const Sheet = styled(Page)`
  text-align: left;
`;

const Heading = styled.h1`
  margin: 0;
  font-family: var(--font-mono);
  font-weight: 700;
  font-size: 26px;
  letter-spacing: -0.02em;
  color: var(--white);
`;

const Sub = styled.div`
  color: var(--amber-dim);
  margin: 4px 0 14px;
`;

const H2 = styled.h2`
  margin: 0 0 8px;
  font-size: 14px;
  color: var(--white);
`;

const SubH = styled.h3`
  margin: 16px 0 8px;
  font-size: 12px;
  color: var(--gold-bright);
  font-weight: 400;
`;

const P = styled.p`
  margin: 0 0 10px;
  max-width: 62ch;
  b { color: var(--white); font-weight: 400; }
  i { color: var(--gold-bright); font-style: normal; }
`;

const Letter = styled.div`
  max-width: 62ch;
  p { margin: 0 0 10px; }
  b { color: var(--white); font-weight: 400; }
`;

const Sign = styled.div`
  margin-top: 14px;
  color: var(--white);
  line-height: 1.5;
`;

const Note = styled.div`
  margin-top: 10px;
  padding: 8px 10px;
  border-left: 2px solid var(--gold);
  background: var(--panel);
  color: var(--amber-dim);
  max-width: 62ch;
  b { color: var(--gold-bright); }
`;

// The marks themselves, everywhere they appear: airy, so the shapes read apart.
const glyphType = `
  font-family: var(--font-mono);
  letter-spacing: 0.14em;
  color: var(--gold-bright);
`;

const CellSpan = styled.span`
  ${glyphType}
  white-space: nowrap;
  b { color: var(--white); font-weight: 400; }
`;

const Rail = styled.div`
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
`;

const Carrier = styled.div`
  flex: 1;
  min-width: 92px;
  border: 1px solid var(--panel-border);
  border-radius: 6px;
  padding: 10px 8px;
  text-align: center;
  background: var(--field-bg);

  .g { display: block; font-size: 30px; line-height: 1.1; color: var(--white); }
  .n { display: block; margin-top: 6px; color: var(--gold-bright); }
  .d { display: block; color: var(--amber-dim); }
  .v { display: block; margin-top: 4px; font-size: 10px; color: var(--amber-dim); }
`;

const Anatomy = styled.div`
  display: flex;
  align-items: center;
  gap: 18px;
  flex-wrap: wrap;
  margin: 12px 0;
  padding: 12px;
  border: 1px solid var(--panel-border);
  border-radius: 6px;
  background: var(--field-bg);

  .cell {
    ${glyphType}
    font-size: 34px;
    b { color: var(--white); }
    i { font-style: normal; color: var(--gold); }
  }
  .legs {
    display: flex;
    flex-direction: column;
    gap: 3px;
    color: var(--amber-dim);
    b { color: var(--white); font-weight: 400; }
    b.lit { color: var(--gold-bright); }
    i { ${glyphType} font-style: normal; }
  }
`;

const Band = styled.div`
  margin-bottom: 12px;
`;

const BandHead = styled.div`
  display: flex;
  align-items: baseline;
  gap: 8px;
  padding-bottom: 5px;
  margin-bottom: 6px;
  border-bottom: 1px solid var(--panel-border);

  .g { ${glyphType} font-size: 16px; color: var(--white); width: 1.6ch; }
  .n { color: var(--white); }
  .h { font-size: 11px; }
`;

const Chart = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(74px, 1fr));
  gap: 4px;
`;

const Slot = styled.div`
  display: flex;
  align-items: baseline;
  gap: 7px;
  padding: 3px 6px;
  border-radius: 4px;
  background: var(--panel);

  .ch { color: var(--white); width: 1.4ch; flex-shrink: 0; }
`;

const Rule = styled.div`
  margin: 10px 0;
  padding: 10px 12px;
  border: 1px solid var(--panel-border);
  border-radius: 6px;
  background: var(--field-bg);
  overflow-x: auto;

  code {
    ${glyphType}
    font-size: 13px;
    line-height: 1.9;
    white-space: nowrap;
  }
`;

const Trace = styled.table`
  width: 100%;
  border-collapse: collapse;
  font-size: 11px;

  th {
    text-align: left;
    font-weight: 400;
    color: var(--amber-dim);
    border-bottom: 1px solid var(--panel-border);
    padding: 4px 8px 4px 0;
  }
  td {
    padding: 3px 8px 3px 0;
    color: var(--amber-dim);
    border-bottom: 1px solid rgba(156, 138, 104, 0.1);
  }
  td.ch { color: var(--white); }
  td.live { color: var(--gold-bright); }
`;

// Earth text, then its marks. The pairing repeats often enough to earn a shape.
const Pair = styled.div`
  margin: 8px 0;
  .k { display: block; color: var(--white); }
  .v { display: block; ${glyphType} font-size: 13px; line-height: 1.8; word-break: break-all; }
  .c { display: block; margin-top: 2px; max-width: 62ch; font-size: 11px; }
  .c b { ${glyphType} font-weight: 400; }
`;

const Phrase = styled.div`
  padding: 8px 0;
  border-bottom: 1px solid rgba(156, 138, 104, 0.12);
  &:last-child { border-bottom: none; }

  .en { display: block; color: var(--white); }
  .st {
    display: block;
    ${glyphType}
    color: var(--amber-text);
    font-size: 13px;
    line-height: 1.8;
    word-break: break-all;
  }
  .li {
    display: block;
    ${glyphType}
    font-size: 13px;
    line-height: 1.8;
    word-break: break-all;
  }
`;

const Field = styled.div`
  margin-bottom: 8px;
  label {
    display: block;
    margin-bottom: 4px;
    color: var(--amber-dim);
    font-size: 11px;
  }
`;

const Toggle = styled.div`
  display: flex;
  gap: 6px;
  margin-bottom: 8px;

  button {
    background: transparent;
    border: 1px solid var(--panel-border);
    border-radius: 14px;
    padding: 4px 10px;
    font-size: 11px;
    color: var(--amber-dim);
    cursor: pointer;
    &:hover { color: var(--white); }
    &.on { border-color: var(--gold); color: var(--gold-bright); background: var(--panel-hover); }
  }
`;

const Out = styled.div`
  min-height: 44px;
  padding: 10px 12px;
  border: 1px solid var(--panel-border);
  border-radius: 6px;
  background: var(--ink);
  ${glyphType}
  font-size: 14px;
  line-height: 1.9;
  word-break: break-all;

  &.earth {
    color: var(--white);
    letter-spacing: 0.01em;
  }
`;

const Seal = styled.div`
  margin-top: 6px;
  font-size: 11px;
  color: ${p => (p.$ok === false ? '#ff8a8a' : p.$ok ? 'var(--gold-bright)' : 'var(--amber-dim)')};
`;

export default Language;
